<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class CreateAwardsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('awards', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('sector_id');
            $table->foreign('sector_id')->references('id')->on('sectors')->onDelete('cascade');
            $table->unsignedBigInteger('award_program_id');
            $table->foreign('award_program_id')->references('id')->on('award_programs')->onDelete('cascade');
            $table->string('name');
            $table->text('description');
            $table->text('criteria')->nullable();
            $table->timestamps();
        });

        $awards = [
            ['name'=> 'Risk & Compliance Champion', 'description'=>'This Award is presented to the organization that has proven itself to be able to lead ground-breaking Risk Management and Compliance approach that tackles the challenges and exploit opportunities in today’s world.', 'criteria'=>'Please nominate a bank successful in delivering superior values to the clients and itself through integrated risk management and compliance.', 'sector_id'=> 1,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Risk & Compliance Educator', 'description'=>'The most innovative risk and compliance educator in Nigeria. This award will be given to the organization that has invented and implemented new, innovative ways to learn Risk Management and Compliance.', 'criteria'=>'Please nominate a bank successful in delivering and using innovative form of risk and compliance education methods such as training techniques, e-learning platforms, workshops, seminars or any other form of learning.', 'sector_id'=> 1,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Anti-Bribery & Corruption', 'description'=>'An award to recognise the achievements of an organization for their leadership in the fight against Bribery and Corruption.', 'criteria'=>'Please nominate a bank widely known for promoting anti-bribery and corruption practices.', 'sector_id'=> 1,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Fraud Prevention', 'description'=>'An award to acknowledge the efforts of an organisation in the prevention of Fraud in any business or public sector activity.', 'criteria'=>'Please nominate a bank successful in preventing Fraud or minimizing the occurrence of fraud in their organisation through effective controls and risk aware employees.', 'sector_id'=> 1,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Visionary Awards', 'description'=>'An award to recognise an organisation whose work demonstrates any or all qualities of exceptional foresight, creativity, advocacy, and vision, that furthers the research and development of GRC & FC Prevention capabilities.', 'criteria'=>'Please nominate a bank successful in demonstrating creativity, advocacy, and vision, that furthers the research and development of GRC & Fin. Crime Prevention.', 'sector_id'=> 2,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Practice Leader Awards', 'description'=>'An award to recognise an organisation who demonstrates excellence in the practice of Good Governance, Risk Management, and Compliance as well as improvement of their financial crime prevention capability.', 'criteria'=>'An award to recognise an organisation who demonstrates excellence in the practice of Good Governance, Risk Management, and Compliance as well as improvement of their financial crime prevention capability.', 'sector_id'=> 2,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Employer of the Year', 'description'=>'This award will recognise an organisation that has the wellbeing of its employees at its core.', 'criteria'=>'Please nominate a bank that has successfully created and maintained a supportive working environment that has a real commitment and understanding of its employees. The Bank must have a culture of transparency and openness, with opportunities for learning and progression, the outcome of which will be an engaged, motivated and satisfied workforce.', 'sector_id'=> 3,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'AML Employer of the Year', 'description'=>'An award to promote the fight against Money Laundering by recognizing the efforts of an organisation making significant progress in prevention of illicit monies entering the banking systems.', 'criteria'=>'Please nominate a bank successful in the prevention of illicit monies entering the banking systems and in taking proactive steps to improve their financial crime prevention capability.', 'sector_id'=> 3,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Risk management Team of the Year', 'description'=>'This award recognises a team in an organisation with the best collective achievement in risk mitigation within an organisation. This team reacts positively to regulatory developments and whose influence has resulted in their organisation leading the way in new risk management strategies.', 'criteria'=>'Please nominate a bank that has been successful in transforming the overall organization performance through an effective Risk Management Process.', 'sector_id'=> 3,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Compliance Officer of the year', 'description'=>'The Chief Compliance Officer of the Year Award will recognise an individual working within an organisation that goes above and beyond to ensure compliance is at the forefront of the day-to-day running of the business.', 'criteria'=>'Please nominate a bank whose CCO (Chief Compliance Officer) has been successful in leading his/her team using innovative solutions, whilst ensuring that their business is complying with the ever-changing landscape when it comes to compliance.', 'sector_id'=> 3,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Compliance Team of the Year', 'description'=>'This award recognizes a team inside an organisation that proactively embraces the culture of compliance. This team reacts positively to regulatory developments and whose influence has resulted in their organisation leading the way in new compliance regimes.', 'criteria'=>'Please nominate a bank whose Compliance Team has successfully created a culture of compliance, engaged with other parts of the organisation, initiation of departmental or individual training, and changing business practice within the organisation and engaging more broadly with the industry, including trade associations.', 'sector_id'=> 3,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Risk Officer of the Year', 'description'=>'The aspects that need to be recognized in this individual include the ability to effectively communicate the importance of Risk Management within the corporate structure, the ability to seek innovative approaches for solving complex problems, and the possession of outstanding leadership skills & ability to help others develop quality Risk Management programs.', 'criteria'=>'Please nominate a bank whose CRO (Chief Risk Officer) has been successful in communicating the importance of risk management within the corporate structure, successful in using innovative approaches for solving the challenges and problems in implementing risk management and the possession of leadership skills and ability to help organizations develop quality risk management programs.', 'sector_id'=> 3,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'MLRO or Head of Anti-Financial Crime of the Year', 'description'=>'This award recognises the work of a Money Laundering Reporting Officer in a Bank or Head of Anti-Financial Crime in a Bank either through the challenges that they have had to face and mastered or through the actions taken to bring benefit to their organisation or the industry.', 'criteria'=>'Please nominate a bank whose Money Laundering Reporting Officer in a Bank or Head of Anti-Financial Crime has been successful in fighting against Money Laundering by making significant progress in the prevention of illicit monies entering the banking systems.', 'sector_id'=> 3,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Employer of the Year', 'description'=>'This award will recognise an organisation that has the wellbeing of its employees at its core.', 'criteria'=>'Please nominate an Insurance Company that has successfully created and maintained a supportive working environment that has a real commitment and understanding of its employees. The Insurance Company must have a culture of transparency and openness, with opportunities for learning and progression, the outcome of which will be an engaged, motivated and satisfied workforce.', 'sector_id'=> 4,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Risk Officer of the Year', 'description'=>'The aspects that need to be recognized in this individual include the ability to effectively communicate the importance of Risk Management within the corporate structure, the ability to seek innovative approaches for solving complex problems, and the possession of outstanding leadership skills & ability to help others develop quality Risk Management programs.', 'criteria'=>'Please nominate an Insurance Company whose CRO (Chief Risk Officer) has been successful in communicating the importance of risk management within the corporate structure, successful in using innovative approaches for solving the challenges and problems in implementing risk management and the possession of leadership skills and ability to help organizations develop quality risk management programs.', 'sector_id'=> 4,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Fraud Prevention', 'description'=>'An award to acknowledge the efforts of an Insurance Company in the prevention of Fraud in any business activity.', 'criteria'=>'Please nominate an Insurance Company successful in preventing Fraud or minimizing the occurrence of fraud in their organisation through effective controls and risk aware employees.', 'sector_id'=> 5,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Employer of the Year', 'description'=>'This award will recognise an organisation that has the wellbeing of its employees at its core.', 'criteria'=>'Please nominate a Fintech Company that has successfully created and maintained a supportive working environment that has a real commitment and understanding of its employees. The Fintech must have a culture of transparency and openness, with opportunities for learning and progression, the outcome of which will be an engaged, motivated and satisfied workforce.', 'sector_id'=> 6,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'AML Employer of the Year', 'description'=>'An award to promote the fight against Money Laundering by recognizing the efforts of an organisation making significant progress in prevention of illicit monies entering the banking systems.', 'criteria'=>'Please nominate a Fintech successful in the prevention of illicit monies entering the banking systems and in taking proactive steps to improve their financial crime prevention capability.', 'sector_id'=> 6,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Compliance Officer of the Year', 'description'=>'The Chief Compliance Officer of the Year Award will recognise an individual working within an organisation that goes above and beyond to ensure compliance is at the forefront of the day-to-day running of the business.', 'criteria'=>'Please nominate a FinTech whose CCO (Chief Compliance Officer) has been successful in leading his/her team using innovative solutions, whilst ensuring that their business is complying with the ever-changing landscape when it comes to compliance.', 'sector_id'=> 6,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Risk Officer of the Year', 'description'=>'The aspects that need to be recognized in this individual include the ability to effectively communicate the importance of Risk Management within the corporate structure, the ability to seek innovative approaches for solving complex problems, and the possession of outstanding leadership skills & ability to help others develop quality Risk Management programs.', 'criteria'=>'Please nominate a Fintech whose CRO (Chief Risk Officer) has been successful in communicating the importance of risk management within the corporate structure, successful in using innovative approaches for solving the challenges and problems in implementing risk management and the possession of leadership skills and ability to help organizations develop quality risk management programs.', 'sector_id'=> 6,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Employer of the Year', 'description'=>'This award will recognise an organisation that has the wellbeing of its employees at its core.', 'criteria'=>'Please nominate a Micro Finance Bank that has successfully created and maintained a supportive working environment that has a real commitment and understanding of its employees. The Micro Finance Bank must have a culture of transparency and openness, with opportunities for learning and progression, the outcome of which will be an engaged, motivated and satisfied workforce.', 'sector_id'=> 7,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'AML Employer of the Year', 'description'=>'An award to promote the fight against Money Laundering by recognizing the efforts of an organisation making significant progress in prevention of illicit monies entering the banking systems. Also, to recognise organisation(s) taking proactive steps to improve their financial crime prevention capability.', 'criteria'=>'Please nominate a Micro Finance Bank successful in the prevention of illicit monies entering the banking systems and in taking proactive steps to improve their financial crime prevention capability.', 'sector_id'=> 7,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Compliance Officer of the Year', 'description'=>'The Chief Compliance Officer of the Year Award will recognise an individual working within an organisation that goes above and beyond to ensure compliance is at the forefront of the day-to-day running of the business.', 'criteria'=>'Please nominate a Micro Finance Bank whose CCO (Chief Compliance Officer) has been successful in leading his/her team using innovative solutions, whilst ensuring that their business is complying with the ever-changing landscape when it comes to compliance.', 'sector_id'=> 7,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Risk Officer of the Year', 'description'=>'The aspects that need to be recognized in this individual include the ability to effectively communicate the importance of Risk Management within the corporate structure, the ability to seek innovative approaches for solving complex problems, and the possession of outstanding leadership skills & ability to help others develop quality Risk Management programs.', 'criteria'=>'Please nominate a Micro Finance Bank whose CRO (Chief Risk Officer) has been successful in communicating the importance of risk management within the corporate structure, successful in using innovative approaches for solving the challenges and problems in implementing risk management and the possession of leadership skills and ability to help organizations develop quality risk management programs.', 'sector_id'=> 7,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Employer of the Year', 'description'=>'This award will recognise an organisation that has the wellbeing of its employees at its core.', 'criteria'=>'Please nominate an Asset Management Company that has successfully created and maintained a supportive working environment that has a real commitment and understanding of its employees. The Asset Management Company must have a culture of transparency and openness, with opportunities for learning and progression, the outcome of which will be an engaged, motivated and satisfied workforce.', 'sector_id'=> 8,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'AML Employer of the Year', 'description'=>'An award to promote the fight against Money Laundering by recognizing the efforts of an organisation making significant progress in prevention of illicit monies entering the banking systems. Also, to recognise organisation(s) taking proactive steps to improve their financial crime prevention capability.', 'criteria'=>'Please nominate an Asset Management Company successful in the prevention of illicit monies entering the banking systems and in taking proactive steps to improve their financial crime prevention capability.', 'sector_id'=> 8,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Compliance Officer of the Year', 'description'=>'Please nominate an Asset Management Company successful in the prevention of illicit monies entering the banking systems and in taking proactive steps to improve their financial crime prevention capability.', 'criteria'=>'Please nominate an Asset Management Company whose CCO (Chief Compliance Officer) has been successful in leading his/her team using innovative solutions, whilst ensuring that their business is complying with the ever-changing landscape when it comes to compliance.', 'sector_id'=> 8,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Risk Officer of the Year', 'description'=>'The aspects that need to be recognized in this individual include the ability to effectively communicate the importance of Risk Management within the corporate structure, the ability to seek innovative approaches for solving complex problems, and the possession of outstanding leadership skills & ability to help others develop quality Risk Management programs.', 'criteria'=>'Please nominate an Asset Management Company whose CRO (Chief Risk Officer) has been successful in communicating the importance of risk management within the corporate structure, successful in using innovative approaches for solving the challenges and problems in implementing risk management and the possession of leadership skills and ability to help organizations develop quality risk management programs.', 'sector_id'=> 8,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Employer of the Year', 'description'=>'This award will recognise an organisation that has the wellbeing of its employees at its core.', 'criteria'=>'Please nominate a Pension Fund Operator that has successfully created and maintained a supportive working environment that has a real commitment and understanding of its employees. The Pension Fund Operator must have a culture of transparency and openness, with opportunities for learning and progression, the outcome of which will be an engaged, motivated and satisfied workforce.', 'sector_id'=> 9,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'AML Employer of the Year', 'description'=>'An award to promote the fight against Money Laundering by recognizing the efforts of an organisation making significant progress in prevention of illicit monies entering the banking systems. Also, to recognise organisation(s) taking proactive steps to improve their financial crime prevention capability.', 'criteria'=>'Please nominate a Pension Fund Operator successful in the prevention of illicit monies entering the banking systems and in taking proactive steps to improve their financial crime prevention capability.', 'sector_id'=> 9,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Compliance Officer of the Year', 'description'=>'The Chief Compliance Officer of the Year Award will recognise an individual working within an organisation that goes above and beyond to ensure compliance is at the forefront of the day-to-day running of the business.', 'criteria'=>'Please nominate a Pension Fund Operator whose CCO (Chief Compliance Officer) has been successful in leading his/her team using innovative solutions, whilst ensuring that their business is complying with the ever-changing landscape when it comes to compliance.', 'sector_id'=> 9,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Risk Officer of the Year', 'description'=>'The aspects that need to be recognized in this individual include the ability to effectively communicate the importance of Risk Management within the corporate structure, the ability to seek innovative approaches for solving complex problems, and the possession of outstanding leadership skills & ability to help others develop quality Risk Management programs.', 'criteria'=>'Please nominate a Pension Fund Operator whose CRO (Chief Risk Officer) has been successful in communicating the importance of risk management within the corporate structure, successful in using innovative approaches for solving the challenges and problems in implementing risk management and the possession of leadership skills and ability to help organizations develop quality risk management programs.', 'sector_id'=> 9,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC & Anti-Financial Crime Reporter of the Year', 'description'=>'This award is to recognise the media for helping to promote GRC & Anti-Financial Crime.', 'criteria'=>'Please state the name of any Nigerian Reporter that gives updates and analysis on GRC and Anti-FinCrime matters as well as current happening with the main goal to keep public updated.', 'sector_id'=> 10,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC & Anti-Financial Crime TV Channel of the Year', 'description'=>'This award is to recognise the media for helping to promote GRC & Anti-Financial Crime.', 'criteria'=>'Please state the name of any Nigerian TV Channel that gives updates and analysis on GRC and Anti-FinCrime matters as well as current happening with the main goal to keep public updated.', 'sector_id'=> 10,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Best GRC Solution Provider of the Year', 'description'=>'The award recognises GRC solution providers that are doing the most to help financial services firms meet various challenges in credit and operational risk management, enterprise risk management and Compliance. Also the award recognises GRC solution providers who have contributed to the advancement of Risk Management and Compliance knowledge and practice by finding new ways in its implementations.', 'criteria'=>'Please nominate a GRC Solution Provider whose software/solution strengthens the capability in managing risks and ensuring compliance of all applicable rules and regulations.', 'sector_id'=> 11,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Best Financial Crime Prevention Solution Provider of the Year', 'description'=>'The award recognizes Financial Crime Prevention Solution Providers that are doing the most to help identify or minimize financial crime activities in the financial industry. The award recognises Financial Crime Prevention Solution Providers who are outstanding in the areas of service, negotiation, product impact, conflict resolution, strategy and innovation from the software users’ point of view.', 'criteria'=>'Please nominate a Financial Crime Prevention Solution Provider that its sodtware/solution enhances proactive steps to improve financial crime prevention capabilities.', 'sector_id'=> 11,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Best GRC Training Provider of the Year', 'description'=>'The award recognizes Training Providers in the area of Governance, Risk and Compliance who are very versatile and have innovative ways of teaching GRC courses.', 'criteria'=>'Please state a GRC Training Provider that meets these requirements.', 'sector_id'=> 11,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],        
            ['name'=> 'Best Financial Crime Training Provider of the Year', 'description'=>'The award recognizes Training Providers in the area of Financial Crime Prevention who are very versatile and have innovative ways of teaching Financial Crime Prevention courses.', 'criteria'=>'Please state a Financial Crime Prevention Training Provider that meets these requirements.', 'sector_id'=> 11,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],        
            ['name'=> 'Governors', 'description'=>'Leadership Awards for supporting and promoting these initiatives by demonstration of exemplary leadership, implementing effective Governance, Anti-Financial Crime / AML and complying with statutory laws, regulations and standards in their various states (Public sector) in the Country.', 'criteria'=>'Please select a Governor who has show excellence in leadership and implementing effective governance.', 'sector_id'=> 12,'award_program_id' => 1,'created_at' => now(),'updated_at' => now()],
            
            
            ['name'=> 'Risk & Compliance Champion', 'description'=>'This Award is presented to the organization that has proven itself to be able to lead ground-breaking Risk Management and Compliance approach that tackles the challenges and exploit opportunities in today’s world.', 'criteria'=>'Please nominate a bank successful in delivering superior values to the clients and itself through integrated risk management and compliance.', 'sector_id'=> 13,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Risk & Compliance Educator', 'description'=>'The most innovative risk and compliance educator in Nigeria. This award will be given to the organization that has invented and implemented new, innovative ways to learn Risk Management and Compliance.', 'criteria'=>'Please nominate a bank successful in delivering and using innovative form of risk and compliance education methods such as training techniques, e-learning platforms, workshops, seminars or any other form of learning.', 'sector_id'=> 13,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Anti-Bribery & Corruption', 'description'=>'An award to recognise the achievements of an organization for their leadership in the fight against Bribery and Corruption.', 'criteria'=>'Please nominate a bank widely known for promoting anti-bribery and corruption practices.', 'sector_id'=> 13,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Fraud Prevention', 'description'=>'An award to acknowledge the efforts of an organisation in the prevention of Fraud in any business or public sector activity.', 'criteria'=>'Please nominate a bank successful in preventing Fraud or minimizing the occurrence of fraud in their organisation through effective controls and risk aware employees.', 'sector_id'=> 13,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Visionary Awards', 'description'=>'An award to recognise an organisation whose work demonstrates any or all qualities of exceptional foresight, creativity, advocacy, and vision, that furthers the research and development of GRC & FC Prevention capabilities.', 'criteria'=>'Please nominate a bank successful in demonstrating creativity, advocacy, and vision, that furthers the research and development of GRC & Fin. Crime Prevention.', 'sector_id'=> 14,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Practice Leader Awards', 'description'=>'An award to recognise an organisation who demonstrates excellence in the practice of Good Governance, Risk Management, and Compliance as well as improvement of their financial crime prevention capability.', 'criteria'=>'An award to recognise an organisation who demonstrates excellence in the practice of Good Governance, Risk Management, and Compliance as well as improvement of their financial crime prevention capability.', 'sector_id'=> 14,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Employer of the Year', 'description'=>'This award will recognise an organisation that has the wellbeing of its employees at its core.', 'criteria'=>'Please nominate a bank that has successfully created and maintained a supportive working environment that has a real commitment and understanding of its employees. The Bank must have a culture of transparency and openness, with opportunities for learning and progression, the outcome of which will be an engaged, motivated and satisfied workforce.', 'sector_id'=> 15,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'AML Employer of the Year', 'description'=>'An award to promote the fight against Money Laundering by recognizing the efforts of an organisation making significant progress in prevention of illicit monies entering the banking systems.', 'criteria'=>'Please nominate a bank successful in the prevention of illicit monies entering the banking systems and in taking proactive steps to improve their financial crime prevention capability.', 'sector_id'=> 15,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Risk management Team of the Year', 'description'=>'This award recognises a team in an organisation with the best collective achievement in risk mitigation within an organisation. This team reacts positively to regulatory developments and whose influence has resulted in their organisation leading the way in new risk management strategies.', 'criteria'=>'Please nominate a bank that has been successful in transforming the overall organization performance through an effective Risk Management Process.', 'sector_id'=> 15,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Compliance Officer of the year', 'description'=>'The Chief Compliance Officer of the Year Award will recognise an individual working within an organisation that goes above and beyond to ensure compliance is at the forefront of the day-to-day running of the business.', 'criteria'=>'Please nominate a bank whose CCO (Chief Compliance Officer) has been successful in leading his/her team using innovative solutions, whilst ensuring that their business is complying with the ever-changing landscape when it comes to compliance.', 'sector_id'=> 15,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Compliance Team of the Year', 'description'=>'This award recognizes a team inside an organisation that proactively embraces the culture of compliance. This team reacts positively to regulatory developments and whose influence has resulted in their organisation leading the way in new compliance regimes.', 'criteria'=>'Please nominate a bank whose Compliance Team has successfully created a culture of compliance, engaged with other parts of the organisation, initiation of departmental or individual training, and changing business practice within the organisation and engaging more broadly with the industry, including trade associations.', 'sector_id'=> 15,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Risk Officer of the Year', 'description'=>'The aspects that need to be recognized in this individual include the ability to effectively communicate the importance of Risk Management within the corporate structure, the ability to seek innovative approaches for solving complex problems, and the possession of outstanding leadership skills & ability to help others develop quality Risk Management programs.', 'criteria'=>'Please nominate a bank whose CRO (Chief Risk Officer) has been successful in communicating the importance of risk management within the corporate structure, successful in using innovative approaches for solving the challenges and problems in implementing risk management and the possession of leadership skills and ability to help organizations develop quality risk management programs.', 'sector_id'=> 15,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'MLRO or Head of Anti-Financial Crime of the Year', 'description'=>'This award recognises the work of a Money Laundering Reporting Officer in a Bank or Head of Anti-Financial Crime in a Bank either through the challenges that they have had to face and mastered or through the actions taken to bring benefit to their organisation or the industry.', 'criteria'=>'Please nominate a bank whose Money Laundering Reporting Officer in a Bank or Head of Anti-Financial Crime has been successful in fighting against Money Laundering by making significant progress in the prevention of illicit monies entering the banking systems.', 'sector_id'=> 15,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Employer of the Year', 'description'=>'This award will recognise an organisation that has the wellbeing of its employees at its core.', 'criteria'=>'Please nominate an Insurance Company that has successfully created and maintained a supportive working environment that has a real commitment and understanding of its employees. The Insurance Company must have a culture of transparency and openness, with opportunities for learning and progression, the outcome of which will be an engaged, motivated and satisfied workforce.', 'sector_id'=> 16,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Risk Officer of the Year', 'description'=>'The aspects that need to be recognized in this individual include the ability to effectively communicate the importance of Risk Management within the corporate structure, the ability to seek innovative approaches for solving complex problems, and the possession of outstanding leadership skills & ability to help others develop quality Risk Management programs.', 'criteria'=>'Please nominate an Insurance Company whose CRO (Chief Risk Officer) has been successful in communicating the importance of risk management within the corporate structure, successful in using innovative approaches for solving the challenges and problems in implementing risk management and the possession of leadership skills and ability to help organizations develop quality risk management programs.', 'sector_id'=> 16,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Fraud Prevention', 'description'=>'An award to acknowledge the efforts of an Insurance Company in the prevention of Fraud in any business activity.', 'criteria'=>'Please nominate an Insurance Company successful in preventing Fraud or minimizing the occurrence of fraud in their organisation through effective controls and risk aware employees.', 'sector_id'=> 17,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Employer of the Year', 'description'=>'This award will recognise an organisation that has the wellbeing of its employees at its core.', 'criteria'=>'Please nominate a Fintech Company that has successfully created and maintained a supportive working environment that has a real commitment and understanding of its employees. The Fintech must have a culture of transparency and openness, with opportunities for learning and progression, the outcome of which will be an engaged, motivated and satisfied workforce.', 'sector_id'=> 18,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'AML Employer of the Year', 'description'=>'An award to promote the fight against Money Laundering by recognizing the efforts of an organisation making significant progress in prevention of illicit monies entering the banking systems.', 'criteria'=>'Please nominate a Fintech successful in the prevention of illicit monies entering the banking systems and in taking proactive steps to improve their financial crime prevention capability.', 'sector_id'=> 18,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Compliance Officer of the Year', 'description'=>'The Chief Compliance Officer of the Year Award will recognise an individual working within an organisation that goes above and beyond to ensure compliance is at the forefront of the day-to-day running of the business.', 'criteria'=>'Please nominate a FinTech whose CCO (Chief Compliance Officer) has been successful in leading his/her team using innovative solutions, whilst ensuring that their business is complying with the ever-changing landscape when it comes to compliance.', 'sector_id'=> 18,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Risk Officer of the Year', 'description'=>'The aspects that need to be recognized in this individual include the ability to effectively communicate the importance of Risk Management within the corporate structure, the ability to seek innovative approaches for solving complex problems, and the possession of outstanding leadership skills & ability to help others develop quality Risk Management programs.', 'criteria'=>'Please nominate a Fintech whose CRO (Chief Risk Officer) has been successful in communicating the importance of risk management within the corporate structure, successful in using innovative approaches for solving the challenges and problems in implementing risk management and the possession of leadership skills and ability to help organizations develop quality risk management programs.', 'sector_id'=> 18,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Employer of the Year', 'description'=>'This award will recognise an organisation that has the wellbeing of its employees at its core.', 'criteria'=>'Please nominate a Micro Finance Bank that has successfully created and maintained a supportive working environment that has a real commitment and understanding of its employees. The Micro Finance Bank must have a culture of transparency and openness, with opportunities for learning and progression, the outcome of which will be an engaged, motivated and satisfied workforce.', 'sector_id'=> 19,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'AML Employer of the Year', 'description'=>'An award to promote the fight against Money Laundering by recognizing the efforts of an organisation making significant progress in prevention of illicit monies entering the banking systems. Also, to recognise organisation(s) taking proactive steps to improve their financial crime prevention capability.', 'criteria'=>'Please nominate a Micro Finance Bank successful in the prevention of illicit monies entering the banking systems and in taking proactive steps to improve their financial crime prevention capability.', 'sector_id'=> 19,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Compliance Officer of the Year', 'description'=>'The Chief Compliance Officer of the Year Award will recognise an individual working within an organisation that goes above and beyond to ensure compliance is at the forefront of the day-to-day running of the business.', 'criteria'=>'Please nominate a Micro Finance Bank whose CCO (Chief Compliance Officer) has been successful in leading his/her team using innovative solutions, whilst ensuring that their business is complying with the ever-changing landscape when it comes to compliance.', 'sector_id'=> 19,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Risk Officer of the Year', 'description'=>'The aspects that need to be recognized in this individual include the ability to effectively communicate the importance of Risk Management within the corporate structure, the ability to seek innovative approaches for solving complex problems, and the possession of outstanding leadership skills & ability to help others develop quality Risk Management programs.', 'criteria'=>'Please nominate a Micro Finance Bank whose CRO (Chief Risk Officer) has been successful in communicating the importance of risk management within the corporate structure, successful in using innovative approaches for solving the challenges and problems in implementing risk management and the possession of leadership skills and ability to help organizations develop quality risk management programs.', 'sector_id'=> 19,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Employer of the Year', 'description'=>'This award will recognise an organisation that has the wellbeing of its employees at its core.', 'criteria'=>'Please nominate an Asset Management Company that has successfully created and maintained a supportive working environment that has a real commitment and understanding of its employees. The Asset Management Company must have a culture of transparency and openness, with opportunities for learning and progression, the outcome of which will be an engaged, motivated and satisfied workforce.', 'sector_id'=> 20,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'AML Employer of the Year', 'description'=>'An award to promote the fight against Money Laundering by recognizing the efforts of an organisation making significant progress in prevention of illicit monies entering the banking systems. Also, to recognise organisation(s) taking proactive steps to improve their financial crime prevention capability.', 'criteria'=>'Please nominate an Asset Management Company successful in the prevention of illicit monies entering the banking systems and in taking proactive steps to improve their financial crime prevention capability.', 'sector_id'=> 20,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Compliance Officer of the Year', 'description'=>'Please nominate an Asset Management Company successful in the prevention of illicit monies entering the banking systems and in taking proactive steps to improve their financial crime prevention capability.', 'criteria'=>'Please nominate an Asset Management Company whose CCO (Chief Compliance Officer) has been successful in leading his/her team using innovative solutions, whilst ensuring that their business is complying with the ever-changing landscape when it comes to compliance.', 'sector_id'=> 20,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Risk Officer of the Year', 'description'=>'The aspects that need to be recognized in this individual include the ability to effectively communicate the importance of Risk Management within the corporate structure, the ability to seek innovative approaches for solving complex problems, and the possession of outstanding leadership skills & ability to help others develop quality Risk Management programs.', 'criteria'=>'Please nominate an Asset Management Company whose CRO (Chief Risk Officer) has been successful in communicating the importance of risk management within the corporate structure, successful in using innovative approaches for solving the challenges and problems in implementing risk management and the possession of leadership skills and ability to help organizations develop quality risk management programs.', 'sector_id'=> 20,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Employer of the Year', 'description'=>'This award will recognise an organisation that has the wellbeing of its employees at its core.', 'criteria'=>'Please nominate a Pension Fund Operator that has successfully created and maintained a supportive working environment that has a real commitment and understanding of its employees. The Pension Fund Operator must have a culture of transparency and openness, with opportunities for learning and progression, the outcome of which will be an engaged, motivated and satisfied workforce.', 'sector_id'=> 21,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'AML Employer of the Year', 'description'=>'An award to promote the fight against Money Laundering by recognizing the efforts of an organisation making significant progress in prevention of illicit monies entering the banking systems. Also, to recognise organisation(s) taking proactive steps to improve their financial crime prevention capability.', 'criteria'=>'Please nominate a Pension Fund Operator successful in the prevention of illicit monies entering the banking systems and in taking proactive steps to improve their financial crime prevention capability.', 'sector_id'=> 21,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Compliance Officer of the Year', 'description'=>'The Chief Compliance Officer of the Year Award will recognise an individual working within an organisation that goes above and beyond to ensure compliance is at the forefront of the day-to-day running of the business.', 'criteria'=>'Please nominate a Pension Fund Operator whose CCO (Chief Compliance Officer) has been successful in leading his/her team using innovative solutions, whilst ensuring that their business is complying with the ever-changing landscape when it comes to compliance.', 'sector_id'=> 21,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Chief Risk Officer of the Year', 'description'=>'The aspects that need to be recognized in this individual include the ability to effectively communicate the importance of Risk Management within the corporate structure, the ability to seek innovative approaches for solving complex problems, and the possession of outstanding leadership skills & ability to help others develop quality Risk Management programs.', 'criteria'=>'Please nominate a Pension Fund Operator whose CRO (Chief Risk Officer) has been successful in communicating the importance of risk management within the corporate structure, successful in using innovative approaches for solving the challenges and problems in implementing risk management and the possession of leadership skills and ability to help organizations develop quality risk management programs.', 'sector_id'=> 21,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC & Financial Crime Prevention Visionary Awards', 'description'=>'An award to recognise an organisation whose work demonstrates any or all qualities of exceptional foresight, creativity, advocacy, and vision, that furthers the research and development of GRC & FC Prevention capabilities.', 'criteria'=>'Evidence of success in demonstrating creativity, advocacy, and vision, that furthers the research and development of GRC & FC Prevention.', 'sector_id'=> 21,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            
            ['name'=> 'GRC Woman of the Year in Commercial Banks', 'description'=>'The Women in Governance, Risk and Compliance Awards honour female leaders demonstrating excellence across GRC. These Awards showcase the role models, advocates and mentors, as well as the inspirational women building and leading in the world of GRC. Please nominate a female leader in any of the Commerical Banks in Nigeria that meets this criteria.', 'criteria'=>'', 'sector_id'=> 22,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Woman of the Year in Insurance', 'description'=>'The Women in Governance, Risk and Compliance Awards honour female leaders demonstrating excellence across GRC. These Awards showcase the role models, advocates and mentors, as well as the inspirational women building and leading in the world of GRC. Please nominate a female leader in any of the Insurance Companies in Nigeria that meets this criteria.', 'criteria'=>'', 'sector_id'=> 22,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Woman of the Year in FinTech', 'description'=>'The Women in Governance, Risk and Compliance Awards honour female leaders demonstrating excellence across GRC. These Awards showcase the role models, advocates and mentors, as well as the inspirational women building and leading in the world of GRC. Please nominate a female leader in any of the Fintech Companies in Nigeria that meets this criteria.', 'criteria'=>'', 'sector_id'=> 22,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Woman of the Year in Insurance', 'description'=>'The Women in Governance, Risk and Compliance Awards honour female leaders demonstrating excellence across GRC. These Awards showcase the role models, advocates and mentors, as well as the inspirational women building and leading in the world of GRC. Please nominate a female leader in any of the Microfinance Banks in Nigeria that meets this criteria.', 'criteria'=>'', 'sector_id'=> 22,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Woman of the Year in Insurance', 'description'=>'The Women in Governance, Risk and Compliance Awards honour female leaders demonstrating excellence across GRC. These Awards showcase the role models, advocates and mentors, as well as the inspirational women building and leading in the world of GRC. Please nominate a female leader in any of the Asset Management Firms in Nigeria that meets this criteria.', 'criteria'=>'', 'sector_id'=> 22,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC Woman of the Year in Insurance', 'description'=>'The Women in Governance, Risk and Compliance Awards honour female leaders demonstrating excellence across GRC. These Awards showcase the role models, advocates and mentors, as well as the inspirational women building and leading in the world of GRC. Please nominate a female leader in any of the Pension Industry in Nigeria that meets this criteria.', 'criteria'=>'', 'sector_id'=> 22,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],

            ['name'=> 'GRC & Anti-Financial Crime Reporter of the Year', 'description'=>'This award is to recognise the media for helping to promote GRC & Anti-Financial Crime.', 'criteria'=>'Please state the name of any Nigerian Reporter that gives updates and analysis on GRC and Anti-FinCrime matters as well as current happening with the main goal to keep public updated.', 'sector_id'=> 23,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'GRC & Anti-Financial Crime TV Channel of the Year', 'description'=>'This award is to recognise the media for helping to promote GRC & Anti-Financial Crime.', 'criteria'=>'Please state the name of any Nigerian TV Channel that gives updates and analysis on GRC and Anti-FinCrime matters as well as current happening with the main goal to keep public updated.', 'sector_id'=> 23,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Best GRC Solution Provider of the Year', 'description'=>'The award recognises GRC solution providers that are doing the most to help financial services firms meet various challenges in credit and operational risk management, enterprise risk management and Compliance. Also the award recognises GRC solution providers who have contributed to the advancement of Risk Management and Compliance knowledge and practice by finding new ways in its implementations.', 'criteria'=>'Please nominate a GRC Solution Provider whose software/solution strengthens the capability in managing risks and ensuring compliance of all applicable rules and regulations.', 'sector_id'=> 24,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Best Financial Crime Prevention Solution Provider of the Year', 'description'=>'The award recognizes Financial Crime Prevention Solution Providers that are doing the most to help identify or minimize financial crime activities in the financial industry. The award recognises Financial Crime Prevention Solution Providers who are outstanding in the areas of service, negotiation, product impact, conflict resolution, strategy and innovation from the software users’ point of view.', 'criteria'=>'Please nominate a Financial Crime Prevention Solution Provider that its sodtware/solution enhances proactive steps to improve financial crime prevention capabilities.', 'sector_id'=> 24,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            ['name'=> 'Best GRC Training Provider of the Year', 'description'=>'The award recognizes Training Providers in the area of Governance, Risk and Compliance who are very versatile and have innovative ways of teaching GRC courses.', 'criteria'=>'Please state a GRC Training Provider that meets these requirements.', 'sector_id'=> 24,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],        
            ['name'=> 'Best Financial Crime Training Provider of the Year', 'description'=>'The award recognizes Training Providers in the area of Financial Crime Prevention who are very versatile and have innovative ways of teaching Financial Crime Prevention courses.', 'criteria'=>'Please state a Financial Crime Prevention Training Provider that meets these requirements.', 'sector_id'=> 24,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],        
            ['name'=> 'Governors', 'description'=>'Leadership Awards for supporting and promoting these initiatives by demonstration of exemplary leadership, implementing effective Governance, Anti-Financial Crime / AML and complying with statutory laws, regulations and standards in their various states (Public sector) in the Country.', 'criteria'=>'Please select a Governor who has show excellence in leadership and implementing effective governance.', 'sector_id'=> 25,'award_program_id' => 2,'created_at' => now(),'updated_at' => now()],
            
        ];

        foreach($awards as $award){
            DB::table('awards')->insert($award);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('awards');
    }
}
